apiVersion: v1
kind: Service
metadata:
    name: "atomaks-8e23"
    labels:
        app: "atomaks-8e23"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "atomaks-8e23"